version: '2'

volumes:
  mongo_data: {}

services:
  web:
    build: .
    tty: true
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/app.py

  blockchain_worker:
    build: .
    tty: true
    restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/worker.py blockchain

  confirmation_worker:
    build: .
    tty: true
    restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/worker.py confirmation

  notification_worker:
    build: .
    tty: true
    restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/worker.py notifier

  mongodb:
    image: mongo:3.5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
