version: '2'

volumes:
  mongo_data: {}

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI="mongodb://db:27017/steem_notifier"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/app.py

  mongodb:
    image: mongo:3.5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
