version: '2'

volumes:
  mongo_data: {}

services:
  web:
    build: .
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/steem_notifier
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/app.py

  blockchain_worker:
    build: .
    tty: true
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/steem_notifier
      - TELEGRAM_TOKEN=380184752:AAEObQIeG0ve_IVanUnR-p8GAdW9PRwVL_c
      - MAILGUN_DOMAIN_NAME=example.com
      - MAILGUN_API_KEY=abcdef
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/worker.py blockchain

  confirmation_worker:
    build: .
    tty: true
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/steem_notifier
      - TELEGRAM_TOKEN=380184752:AAEObQIeG0ve_IVanUnR-p8GAdW9PRwVL_c
      - MAILGUN_DOMAIN_NAME=example.com
      - MAILGUN_API_KEY=abcdef
      - STEEM_WALLET=furion
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    command: python src/worker.py confirmation

  mongodb:
    image: mongo:3.5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
